# Site settings
title: Jake Davies
email: me@jakedavies.info
description: > # 
  Developer, Builder, Experimenter. <br/>
  I am a full stack software developer who loves soccer, RC and electronics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jakedavies.info.com" # the base hostname & protocol for your site
github_username:  jakedavies

# Build settings
markdown: kramdown
